import re
import logging
from langchain_core.messages import HumanMessage, AIMessage, AIMessageChunk

logger = logging.getLogger("denver.core")

async def invoke_graph(agent_app, text: str, chat_id: str | int, is_voice: bool = False, interface: str = "telegram", image_binary: bytes | None = None) -> dict:
    """Invoke the graph and return the full result dict."""
    inputs = {
        "messages": [HumanMessage(content=text)],
        "chat_id": str(chat_id),
        "is_voice": is_voice,
        "image_binary": image_binary,
        "next": "",
        "delegation_count": 0,
        "current_task": "",
        "interface": interface,
    }
    result = await agent_app.ainvoke(
        inputs,
        config={"configurable": {"thread_id": str(chat_id)}},
    )
    return result

async def stream_graph(agent_app, text: str, chat_id: str | int, is_voice: bool = False, interface: str = "telegram", image_binary: bytes | None = None):
    """
    Invokes the graph using astream_events to yield tokens in real time.
    Yields tuples: 
        ("chunk", str) - when a piece of text is generated by the final LLM response
        ("result", dict) - when the graph finishes, yields the final state dict
    """
    inputs = {
        "messages": [HumanMessage(content=text)],
        "chat_id": str(chat_id),
        "is_voice": is_voice,
        "image_binary": image_binary,
        "next": "",
        "delegation_count": 0,
        "current_task": "",
        "interface": interface,
    }
    
    config = {"configurable": {"thread_id": str(chat_id)}}
    
    async for event in agent_app.astream_events(inputs, config=config, version="v2"):
        kind = event["event"]
        
        if kind == "on_chat_model_stream":
            node = event.get("metadata", {}).get("langgraph_node", "")
            tags = event.get("tags", [])
            
            # We filter for the nodes that are Specialists, OR the supervisor fallback logic
            if node in ("infra_node", "workspace_node", "search_node") or "supervisor_chat" in tags:
                chunk = event["data"]["chunk"]
                
                # Check that it's a message chunk, has content, and isn't a tool call reasoning
                if isinstance(chunk, AIMessageChunk) and chunk.content and not chunk.tool_call_chunks:
                    if isinstance(chunk.content, str):
                        yield ("chunk", chunk.content)

    final_state = await agent_app.aget_state(config)
    yield ("result", final_state.values)

def extract_response(result: dict) -> str:
    """Extract the last AI message content from the graph result, stripping tool action prefixes."""
    messages = result.get("messages", [])
    for msg in reversed(messages):
        if isinstance(msg, AIMessage) and msg.content:
            text = msg.content
            # Strip "[Action: ...]" prefix added by specialists
            text = re.sub(r'^\[Action: .*?\]\s*', '', text)
            return text
    return "No pude procesar tu solicitud."
